rdkcentral/Dobby

CMakeLists.txt

Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>

make LEGACY_COMPONENTS setting optional

---

CMakeLists.txt
rdkPlugins/IPC/CMakeLists.txt
rdkPlugins/Logging/CMakeLists.txt
rdkPlugins/Networking/CMakeLists.txt
rdkPlugins/Storage/CMakeLists.txt
rdkPlugins/TestPlugin/CMakeLists.txt

Dobby version updated to 3.0, and plugins to 1.0.

XRE-16079 - Change plugins to versioned shared libraries

---

AppInfrastructure/Public/Dobby/IDobbyProxy.h
client/lib/CMakeLists.txt
client/lib/include/DobbyProxy.h
client/lib/source/DobbyProxy.cpp

Removed dependency of jsoncpp.

RDK-29415 - Add Dobby as backend for ProcessContainers

---

client/tool/source/Main.cpp
daemon/lib/source/DobbyWorkQueue.cpp
utils/source/ContainerId.cpp

- Removed debugging log bloat caused by `DobbyWorkQueue`
- Allow underscores in container names
- Fixed try/catch misuse in DobbyTool
- Improved error handling for `DobbyTool start` with dodgy paths

Various usability improvements

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
Troubleshooting.md

* Add documentation on how to troubleshoot Dobby/containers
* Add templates for issues/PRs

Add troubleshooting docs and github templates

---

rdkPlugins/Networking/README.md

Adds troubleshooting tips for Raspberry Pi 3 builds. Links to issues 49 and 50.
-

Added troubleshooting tip for networking plugin bugs with RPi 3

---

client/tool/source/Main.cpp

Currently, when stopping a container with DobbyTool, the program will exit as soon as Dobby has sent the `crun kill` command to stop the container. However, it can take a few hundred ms for all the container processes to actually stop and for the container to exit. This can be problematic when restarting a container by doing
```
DobbyTool stop xxx && DobbyTool start
```
since the first DobbyTool command can exit before the container has completely stopped, so the subsequent start command will fail.
This PR modifies the DobbyTool stop command to wait for the `DOBBY_CTRL_EVENT_STOPPED` event before exiting. This ensures DobbyTool doesn't exit before the container has fully stopped.
Start a container with DobbyTool.
Attempt to restart the container by running:
```
DobbyTool stop xxx && …
```

Wait for container stop event before exiting DobbyTool

---

CMakeLists.txt
client/tool/source/Main.cpp
daemon/process/CMakeLists.txt
daemon/process/settings/dobby.llama.json
plugins/OpenCDM/source/OpenCDMPlugin.cpp
plugins/OpenCDM/source/OpenCDMPlugin.h
rdkPlugins/Networking/CMakeLists.txt
rdkPlugins/Networking/include/BridgeInterface.h
rdkPlugins/Networking/include/Netlink.h
rdkPlugins/Networking/include/TapInterface.h
rdkPlugins/Networking/source/BridgeInterface.cpp
rdkPlugins/Networking/source/Netfilter.cpp
rdkPlugins/Networking/source/Netlink.cpp
rdkPlugins/Networking/source/NetworkSetup.cpp
rdkPlugins/Networking/source/TapInterface.cpp

Porting changes made in sky-dobby so both repositories are in sync.
-

RDK-30517: Port sky dobby changes

---

CMakeLists.txt
bundle/lib/source/DobbySpecConfig.cpp
bundle/runtime-schemas/defs-plugins.json
rdkPlugins/AppServices/CMakeLists.txt
rdkPlugins/AppServices/source/AppServicesRdkPlugin.cpp
rdkPlugins/AppServices/source/AppServicesRdkPlugin.h

Added the RDK version of the AppServices plugin. 
Prepare a container spec with an "AppServicesRdk" object, use DobbyPluginLauncher to check if the hooks try to add and remove the correct iptables rules.

AS RDK Plugin

---

.lgtm.yml

Add LGTM config file to allow static analysis by https://lgtm.com/

Add LGTM config file

---

CMakeLists.txt

Fix syntax error introduced by merge
Ensure CMake runs without error

Fix CMakeLists.txt syntax error

---

.github/workflows/build.yml

Fix syntax error
```
The workflow is not valid. .github/workflows/build.yml (Line: 15, Col: 11): Unrecognized named-value: 'env'.
```
in GitHub action.
Run GitHub action

Fix syntax error in github action

---

.lgtm.yml

All optional plugins should be built during the LGTM analysis to ensure detection of security issues in all plugins
Perform LGTM analysis

Build all plugins during LGTM analysis

---

daemon/process/settings/dobby.llama.json

Add missing device nodes on Sky builds
See JIRA ticket

AMLOGIC-1677: Add device nodes

---

client/tool/source/Main.cpp

Add new command to DobbyTool - `DobbyTool wait <id> <state>`
When started, will wait until the specified container enters the specified state (either `started` or `stopped`), and will then return. Useful for scripting - similar to `lxc-wait`
* Start DobbyDaemon
* In one terminal, run `DobbyTool wait test stopped`. DobbyTool will keep running.
* In another terminal, start a simple container by running `DobbyTool start test /path/to/bundle`
* Wait for the container to stop
Once the container stops, DobbyTool will exit with the message:
```
Container test has changed state to stopped
```
Repeat to test `DobbyTool wait test started`, which will return once the container is running.

DELIA-50630: Add DobbyTool wait command

---

rdkPlugins/Networking/source/Netfilter.cpp

If `iptables-save` returns no valid rules, Dobby should not segfault. This is an unlikely scenario, and any failures with iptables-save should be investigated, but this change ensures Dobby does not crash.
To mock this scenario, edit `Netfilter::getRuleSet` to return an empty RuleSet(). Without this patch, Dobby will segfault with the a back trace similar to:
```
==11885== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==11885==  Access not within mapped region at address 0x10
==11885==    at 0x5CB25A0: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==11885==    by 0xBC8AB54: Netfilter::ruleInList(std::__cxx11::basic_string<char, std::char_traits<char>, …
```

XIONE-5446: Prevent segfault if iptables-save returns no rules

---

daemon/lib/source/Dobby.cpp
daemon/lib/source/DobbyManager.cpp
daemon/lib/source/DobbyRunC.cpp
daemon/lib/source/DobbyRunC.h

Improve Dobby startup performance
* Manually check for running containers at startup to avoid unnecessary `crun list` call
* Force delete containers in cleanupContainers
Ensure Dobby starts up correctly without hanging

XIONE-6236: Startup performance improvements

---

AppInfrastructure/Common/include/ConditionVariable.h

Now providing negative timeout_time for condition variable wait will result in immediate timeout instead of crash.
Simulate a delay in container launch. Edit the networking plugin to add a sleep in the CreateRuntime() OCI hook
```
bool NetworkingPlugin::createRuntime()
{
AI_LOG_FN_ENTRY();
std::this_thread::sleep_for(std::chrono::seconds(3));
```
Start the container, there should be no crash. Without this fix there is high probability of getting this message, with DobbyDaemon crash:
```
0000000528.408709 <T-13219> NFO: < M:ConditionVariable.h F:wait_for L:200 > >>>> -215201102
terminate called after throwing an instance of 'std::system_error'
what(): Invalid argument
Aborted
```

LLAMA-4043 Fixed negative timeout crash.

---

daemon/lib/source/DobbyManager.cpp
daemon/lib/source/DobbyRunC.cpp
daemon/lib/source/DobbyRunC.h

Revert "XIONE-6236 Create timeout for RuncCreate"

---

CMakeLists.txt

Release Dobby version 3.1.0 (2107_sprint)
Perform full validation

RDK-34085: Release 3.1.0

---

CMakeLists.txt
daemon/lib/source/DobbyManager.cpp
daemon/lib/source/DobbyRunC.cpp
daemon/lib/source/DobbyRunC.h

Cherry pick changes from:
* https://github.com/rdkcentral/Dobby/pull/157
* https://github.com/rdkcentral/Dobby/pull/153
to the release 3.1 branch as part of ticket XIONE-6236
Create new point release - v3.1.1
Full regression testing

Release 3.1.1

---

pluginLauncher/lib/include/DobbyRdkPluginManager.h
pluginLauncher/lib/source/DobbyRdkPluginManager.cpp

Revert "XIONE-7154 Plugin launcher hook execution timeout"

---

CMakeLists.txt
daemon/lib/source/DobbyContainer.h
daemon/lib/source/DobbyManager.cpp
daemon/lib/source/DobbyManager.h
daemon/lib/source/DobbyRunC.cpp
daemon/lib/source/DobbyRunC.h

Cherry-pick changes from:
* https://github.com/rdkcentral/Dobby/pull/173
* https://github.com/rdkcentral/Dobby/pull/174
* https://github.com/rdkcentral/Dobby/pull/175
Hotfix release for XIONE-7775
See JIRA ticket

Release v3.2.1

---

rdkPlugins/Storage/source/LoopMountDetails.cpp

Minor bugfixes from the previous PR.

LLAMA-5905: Feature/lldev-17791 shared private storage for apps

---

rdkPlugins/Networking/source/NetworkSetup.cpp

Previously routing was always added to IPv6 version, regardless of IP version being actually used. Now it can be done based on selected version. But it is disabled as bridge itself creates wider rule with higher priority already, so it wouldn't be used either way.
Run any container with network plugin in `Nat` mode. There should be a rule:
`2080:d0bb:1e::/64 dev dobby0 proto kernel metric 256 pref medium`
But there should no longer be per-container rule like:
`2080:d0bb:1e::6440:b02 dev dobby0  metric 1024
2080:d0bb:1e::6440:b03 dev dobby0  metric 1024 `

XIONE-8438 Removed unnecessary IPv6 routing

---

CMakeLists.txt

Version incremented for release 3.5.0.
Check version with 'DobbyDaemon --version'.

RDK-37599: Incremented version to 3.5.0

---

CMakeLists.txt

update version info in CMakeLists.txt
- [x ] Other (doesn't fit into the above categories - e.g. documentation updates)

increment version number  to v3.5.1

---

AppInfrastructure/Common/include/ConditionVariable.h
CMakeLists.txt
daemon/lib/source/DobbyManager.cpp

Release Dobby v3.5.1
fixes for RDKTV-19597 and RDKTV-19656
See Jira tickets

Dobby Patch Release v3.5.1

---

CMakeLists.txt

Release Dobby v3.6.0
Perform standard QA testing

RDK-39278: Dobby Release v3.6.0

---

.github/workflows/build.yml
bundle/lib/include/DobbySpecConfig.h
bundle/lib/source/DobbySpecConfig.cpp
rdkPlugins/LocalTime/source/LocalTimePlugin.cpp
settings/include/IDobbySettings.h
settings/include/Settings.h
settings/source/Settings.cpp

Added plugin data in the settings file and fixed build issues
Check whether the data added in rdkPlugins is correctly set in config.json

RDK-41482 : make localtime symlink path configurable

---

CMakeLists.txt

update version info in CMakeLists.txt

increment version number to v3.6.1

---

.github/workflows/build.yml
CMakeLists.txt
bundle/lib/include/DobbySpecConfig.h
bundle/lib/source/DobbySpecConfig.cpp
bundle/runtime-schemas/defs-plugins.json
pluginLauncher/tool/source/Main.cpp
rdkPlugins/LocalTime/README.md
rdkPlugins/LocalTime/source/LocalTimePlugin.cpp
settings/include/IDobbySettings.h
settings/include/Settings.h
settings/source/Settings.cpp

Release Dobby v3.6.1
fixes for ONEM-29861 and RDK-41482
See Jira tickets

Dobby Patch Release v3.6.1

---

.github/workflows/build.yml
CMakeLists.txt
gtest/DobbyUtilsTest/CMakeLists.txt
gtest/DobbyUtilsTest/tests/ContainerIdTest.cpp
gtest/DobbyUtilsTest/tests/DobbyTimerTests.cpp
gtest/DobbyUtilsTest/tests/DobbyUtilsTest.cpp

Add unit test for DobbyUtils using Gtest framework
Check the github workflow actions whether the unit tests ran successfully

RDK-37030: Unit test for DobbyUtils

---

.github/workflows/build.yml
CMakeLists.txt
gtest/DobbyUtilsTest/CMakeLists.txt
gtest/DobbyUtilsTest/tests/ContainerIdTest.cpp
gtest/DobbyUtilsTest/tests/DobbyTimerTests.cpp
gtest/DobbyUtilsTest/tests/DobbyUtilsTest.cpp

Add unit test for DobbyUtils in release branch

Patch release for Unit test

---

CMakeLists.txt

update version info in CMakeLists.txt

increment version number to v3.6.2

---

CMakeLists.txt

Increment version number to v3.6.3
- [x ] Other (doesn't fit into the above categories - e.g. documentation updates)

Increment version number to v3.6.3

---

daemon/process/dobby.service

Add requirement for dbus.service in dobby.service
Stop dbus service and observe if dobby will be stopped immediately.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] The base Bitbake recipe (`meta-rdk-ext/recipes-containers/dobby/dobby.bb`) must be modified to support the changes in this PR (beyond updating `SRC_REV`)

SERXIONE-1401: Add requirement for dbus.service in dobby.service

---

CMakeLists.txt

Increment version number to v3.6.4
- [ x ] Other (doesn't fit into the above categories - e.g. documentation updates)

Increment version number to v3.6.4

---

CMakeLists.txt
daemon/process/dobby.service

Added dependency to dbus.service.
Increment version number to v3.6.4.

Added dependency to dbus.service.

---

CMakeLists.txt

Increment version number to v3.6.5

Increment version number to v3.6.5

---

CMakeLists.txt

Dobby Release v3.7.0

---

README.md

Documentation link corrected. Typo corrected.
Check the README.md

Documentation link corrected

---

bundle/lib/source/DobbyConfig.cpp

Log about enabling strace corrected.
Check dobby logs wehen launching app with enabled strace.

Log about enabling strace corrected.

---

settings/source/Settings.cpp

Added logging strace settings.
Check logs.

Added logging strace settings

---

CMakeLists.txt

Update version info in CMakeLists.txt

Update version to v3.7.1

---

daemon/lib/source/DobbyManager.cpp

The mContainerStoppedCb is called too early. When running containers on read-only mounted dm-veritfy rootfs, those rootfs are un-mounted when mContainerStoppedCb is called. But if this is called too early we get error:
Device or resource busy.
So moving the call to mContainerStoppedCb to the very end of DobbyManager::onChildExit() so that the extra logic about "tracking any executed processes inside the container" happens BEFORE calling mContainerStoppedCb.
This was the failing scenario:
1. start doom DAC app (rootfs on dm-verity read-only mount)
2. stop DAC app
3. keep trying step 1-2 until step 1 fails
The logging shows that the rootfs could not be unmounted
in the last step 2. (Device or resource busy)
-

ONEM-32702 Delay calling mContainerStoppedCb until very end

---

CMakeLists.txt

Update version to v3.7.2

---

unit_tests/L1_testing/mocks/ContainerId.h
unit_tests/L1_testing/mocks/ContainerIdMock.h
unit_tests/L1_testing/mocks/DobbyEnv.h
unit_tests/L1_testing/mocks/DobbyIPCUtils.h
unit_tests/L1_testing/mocks/DobbyIPCUtilsMock.h
unit_tests/L1_testing/mocks/DobbyManagerMock.h
unit_tests/L1_testing/mocks/DobbyTemplate.h
unit_tests/L1_testing/mocks/DobbyUtils.h
unit_tests/L1_testing/mocks/DobbyUtilsMock.h
unit_tests/L1_testing/mocks/DobbyWorkQueue.h
unit_tests/L1_testing/mocks/IIpcService.h
unit_tests/L1_testing/mocks/IIpcServiceMock.h
unit_tests/L1_testing/mocks/IpcCommon.h
unit_tests/L1_testing/mocks/IpcFileDescriptor.h
unit_tests/L1_testing/mocks/IpcVariantList.cpp
unit_tests/L1_testing/mocks/IpcVariantList.h
unit_tests/L1_testing/tests/DobbyManagerTest/DaemonDobbyManagerTest.cpp
unit_tests/L1_testing/tests/DobbyTest/DaemonDobbyTests.cpp

Completed Test APIs for below Dobby Functions:
1.Dobby::shutdown
2.Dobby::ping
3.Dobby::setLogMethod
4.Dobby::setLogLevel
5.Dobby::getState
6.Dobby::getInfo
7.Dobby::getSpec
8.Dobby::createBundle
9.Dobby::getOCIConfig
10.Dobby::stop
11.Dobby::pause
12.Dobby::Resume
13.Dobby::setAIDbusAddress
14.Dobby::startFromSpec
15.Dobby::startFromBundle
16.Dobby::Exec
18.Dobby::list
NA
- Yes

[RDK-43927] Dobby Unit Test -

---

daemon/lib/source/DobbyManager.cpp

Setting the value of sched_rt_runtime_us to -1 means that real-time tasks may use up to 100% of CPU times which could potentially lock up a system.
Therefore, removed the piece of code in DobbyManager where sched_rt_runtime_us is set to -1, so that the default value 950000 (95% of CPU bandwidth) will be set, allowing 5% of CPU time to be used by non-realtime tasks. This 5% of CPU time should be enough to get rid of the rogue processes.
Reference : https://access.redhat.com/solutions/1604133
Check whether containerized apps runs fine

Setting sched_rt_runtime_us to -1 is dangerous

---

develop/vagrant/Vagrantfile

Added support for unit tests building in Vagrant.
Build and run unit tests in Vagrant dev env.

Added support for unit tests building in Vagrant

---

CMakeLists.txt

RDK-45299: Update version to v3.8.1

---

CMakeLists.txt
daemon/lib/source/DobbyManager.cpp

RDK-45299: startContainerFromSpec fix

RDK-45299: Release v3.8.1

---

CMakeLists.txt

Update version to 3.9.0
Confirm version is reported as 3.9.0

updated version to 3.9.0

---

daemon/lib/source/DobbyManager.cpp

RDK-45706 Fix out of date list of PIDs to hibernate
DobbyTool hibernate --delay=< ms> <container id>

RDK-45706 Fix out of date list of PIDs to hibernate

---

CMakeLists.txt

RDK-47572: Updated version to 3.10.0

RDK-47572: Updated version to 3.10.0

---

CMakeLists.txt

Update version to v3.10.1

---

.github/workflows/L1-tests.yml
.github/workflows/L2-tests.yml
CMakeLists.txt
rdkPlugins/Storage/source/DynamicMountDetails.cpp
tests/L2_testing/dobby_specs/wget-private.json
tests/L2_testing/test_runner/runner.py
tests/L2_testing/test_runner/test_utils.py

Release Dobby v3.10.1
fixes for RDKTV-26826 and RDK-47795

Dobby Patch Release v3.10.1

---

CMakeLists.txt

Update version to v3.10.2

---

.github/workflows/L2-tests.yml

Fix for github workflow check error

---

CMakeLists.txt

Update version to v3.11.0

---

develop/vagrant/memcr/start_memcr.sh

Add libencrypt.so preload to the memcr launch params
Run L2 unit tests
- no

Fix L2 tests for memcr

---

rdkPlugins/Minidump/source/Minidump.cpp

added firebolt state to the minidump filename if annotation is found
crash the process running inside the container and check the minidump filename
```
root@xione-sercomm:~# DobbyTool annotate 879 fireboltState background
annotate successful for container '879'
root@xione-sercomm:~# DobbyTool info 879
{
"annotations" :
{
"fireboltState" : "background"
},
"cpu" :
{
"usage" :
},
{
"cmdline" : "/usr/libexec/wpe-webkit-1.0/WPEWebProcess 10 43 ",
"executable" : "/usr/libexec/wpe-webkit-1.0/WPEWebProcess",
"nsPid" : 40,
"pid" : 12552
}
root@xione-sercomm:~# kill -11 12552
2024-12-03T15:07:02.646Z com.sky.as.apps_xumo[3641]:  pid 9 has terminated by signal 15
2024-12-03T15:07:02.717Z DobbyDaemon[3641]:  NFO: runc for container 'com.sky.as.apps_xumo' has quit (pid:12380 status:0x0100) …
```

RDK-54421: updated minidump plugin

---

CMakeLists.txt

Update version to v3.12.0

---

CMakeLists.txt

Update version to v3.12.1

---

AppInfrastructure/Public/Common/Notifier.h
CMakeLists.txt
daemon/lib/source/DobbyManager.cpp
daemon/lib/source/include/DobbyLogRelay.h
pluginLauncher/lib/include/DobbyRdkPluginUtils.h
rdkPlugins/Storage/source/Storage.cpp

Dobby Patch Release v3.12.1

---

CMakeLists.txt

RDK-56428: Update version to v3.13

---

CMakeLists.txt

updated revision to v3.12.2

---

.github/workflows/L2-tests.yml
develop/vagrant/Vagrantfile

Fix memcr patching in L2 
run L2
- No

Fix memcr patching in L2 tests

---

CMakeLists.txt

RDK-57548: Update version to v3.14

---

CMakeLists.txt

Update version to v3.14.1

---

CMakeLists.txt

Update version to v3.15
