- daemon/lib/source/syshooks/GpuMemoryHook.cpp
We see the following compilation error when compiling Dobby with _arm-rdk-linux-gnueabi-gcc (GCC) 6.4.0_
```
| In file included from /mnt/home/goruklu/workspace/arrisXi6-2006/build-arrisxi6/tmp/sysroots/arrisxi6/usr/include/fcntl.h:314:0,
|                  from /mnt/home/goruklu/workspace/arrisXi6-2006/build-arrisxi6/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/dobby/1.0-r0/git/daemon/lib/source/syshooks/GpuMemoryHook.cpp:31:
| In function 'int openat(int, const char*, int, ...)',
|     inlined from 'bool GpuMemoryHook::writeCgroupFile(const ContainerId&, const string&, size_t)' at /mnt/home/goruklu/workspace/arrisXi6-2006/build-arrisxi6/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/dobby/1.0-r0/git/daemon/lib/source/syshooks/GpuMemoryHook.cpp:119:87:
| …
```
> fix compilation error with missing mode paramter in openat() call

- daemon/lib/source/DobbyManager.cpp
Fixed problem where:
`0000022938.529870 ERR: < M:DobbyManager.cpp F:onChildExit L:1942 > waitpid failed for pid 96201 (10 - No child processes)` error was present
> Waitpid fix

- daemon/lib/source/DobbyManager.cpp
- pluginLauncher/lib/source/DobbyRdkPluginManager.cpp
- pluginLauncher/tool/source/Main.cpp
- rdkPlugins/IPC/source/IpcPlugin.cpp
- rdkPlugins/Logging/source/LoggingPlugin.cpp
- rdkPlugins/Storage/source/Storage.cpp
- rdkPlugins/TestPlugin/source/TestRdkPlugin.cpp
DobbyPluginLauncher and the RDK plugins used a lot of `AI_LOG_INFO`. Reduce many of these to `AI_LOG_DEBUG` to make the log files easier to read.
> Reduce logging severity in RDK plugins

- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyRunC.cpp
Fix "not in stopped state" error from crun when deleting a container that failed to start correctly, and prevent resulting segfault.
> Force delete container if crun delete fails

- NOTICE
Notice file updated for Apache License, Version 2.0 (the "License") from RDK-M
> BLDK-734 : License Header changes for RDK-M

- cmake/libocispec.cmake
CMake 3.15 fails to build Dobby with error:
```
| configure: creating ./config.status
| config.status: creating Makefile
| config.status: creating config.h
| config.status: executing libtool commands
| config.status: executing depfiles commands
| Found wrong amount of files 0, should be 2
| Traceback (most recent call last):
|   File "add_plugin_tables.py", line 149, in <module>
|     process_files()
|   File "add_plugin_tables.py", line 58, in process_files
|     files = find_files()
|   File "add_plugin_tables.py", line 136, in find_files
|     raise IndexError
| IndexError
| -- Configuring incomplete, errors occurred!
```
Fix syntax error preventing schema files from being copied to `libocispec/runtime-schema` with CMake 3.15
> Fix CMake error on CMake 3.15

- AppInfrastructure/Public/Dobby/IDobbyProxy.h
- client/lib/include/DobbyProxy.h
- client/lib/source/DobbyProxy.cpp
- client/tool/source/Main.cpp
- daemon/lib/source/Dobby.cpp
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyManager.h
Add the ability to pass a westeros socket path as an option when starting a container. The socket is then bind-mounted into the container with the following config:
```
{
"source": "/tmp/westeros-0",
"destination": "/tmp/westeros",
"options": [
"bind",
"rw",
"nosuid",
"nodev",
"noexec"
],
"type": "bind"
}
```
Usage:
```
DobbyTool start --westeros-socket /tmp/westeros sleep ./sleepy
```
> [RDK-29360] Add --westeros-socket option

- develop/vagrant/Vagrantfile
Latest sprint branch uses GCC 6.4 - upgrade the Vagrant VM.
Set 6.4 as default instead of 5.4 included with Xenial.
> Update Vagrantfile to use GCC and G++ 6.4 by default

- daemon/lib/source/DobbyRunC.cpp
This work fixes problem found in creation of "RDK-29415 Add Dobby as backend for ProcessContainers", where containers killed by SIGTERM wasn't killed properly.
> RDK-29415 Container kill fix

- daemon/lib/source/DobbyManager.cpp
* without this patch I would get this error when using a config
with zero plugins:
"Could not run preCreation hook as plugin manager is null"
> RDKCMF-8664: fix for configs with zero rdk plugins

- CMakeLists.txt
Using LTO drastically reduces the size of installed files
Enable or disable by using cmake build option ENABLE_LTO
> Add link time optimisation build option

- bundle/lib/source/DobbyConfig.cpp
We need to be able to check whether there is an update to the original OCI config. having a backup allows us to do checksum comparisons.
Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>
> make a backup of the original config.json

- cmake/libocispec.cmake
* commands in execute_process() are executed in parallel
so making the target dirs and copying files in them
must be sequential
> Fix CMake libocispec command sequence

- bundle/lib/source/DobbyConfig.cpp
This moves the creation of config-orig.json to config-dobby.json
so that the written config-dobby.json is a direct copy of the
original configuration file.
See https://github.com/rdkcentral/Dobby/pull/28
> Change original config backup write to avoid writing twice

- plugins/AppServices/source/AppServicesPlugin.cpp
Fix issue where the legacy `AppServices` plugin was not applying the iptables rules after generating them
> Fix legacy AppServices plugin iptables rules

- CMakeLists.txt
- README.md
- client/tool/source/Main.cpp
- daemon/lib/source/Dobby.cpp
- daemon/process/CMakeLists.txt
- daemon/process/dobby.service.in
- daemon/process/settings/dobby.dev_vm.json
- daemon/process/settings/dobby.llama.json
- daemon/process/settings/dobby.xi1.json
- daemon/process/settings/dobby.xi6.json
- daemon/process/source/Main.cpp
- protocol/include/DobbyProtocol.h
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
- settings/include/IDobbySettings.h
- settings/include/Settings.h
- settings/source/Settings.cpp
This used to be in settings, but even then was only partially functional.
Now using the cmake options DOBBY_SERVICE and DOBBY_OBJECT, we can set
the dbus service name and object path across the project.
> Add cmake options to change dbus service name and object path

- NOTICE
Updated License header (removal)  RDK Management copyrights which should be changed to Sky UK and the second one then removed
> BD-821-BLDK-734: Updates In Licences Header

- daemon/lib/source/DobbyManager.cpp
Correctly report a container state as paused
Start & pause a container, then get it's info. The state will show as paused correctly
> Correctly reported paused container state

- daemon/lib/source/DobbyManager.cpp
Change log messages when pausing/resuming container to be more accurate
Start then pause/resume containers
> Improve logging when pause/resume containers

- develop/vagrant/0001-container-truncate-pid-file-before-writing-it.patch
- develop/vagrant/Vagrantfile
Added new crun version v0.15 instead of v0.14.1
-
> Added new crun version.

- bundle/lib/include/DobbySpecConfig.h
- bundle/lib/source/DobbySpecConfig.cpp
Adds the ability to add 1-to-1 copy of the `rdkPlugins` field into Legacy Dobby specs.
Use `-DLEGACY_COMPONENTS=ON` flag.
Use `DobbyBundleGenerator` to generate bundles from specs. Test adding different RDK plugins into the  `rdkPlugins` field to see if they get merged in properly.
It's expected that any plugin data given in the `rdkPlugins` field is merged **over** the data that is processed from the other fields of the spec. I.e. if you have the following Dobby spec:
```
{
...,
"network": "nat",
"rdkPlugins": {
"networking": {
"required": true,
"data": {
"type": "open",
"ipv6": true
}
}
}
}
```
The output bundle's OCI config `rdkPlugins.network` field should be:
```
"networking": {
"required": true,
"data": {
"ipv4": true,
"ipv6": true,
"type": "open"
}
}
```
Note that the `required` …
> RDK-29862 - Add rdkPlugins field to Dobby specs

- bundle/lib/source/DobbySpecConfig.cpp
Fix issue where the data section of the `localtime` plugin was invalid, preventing container startup on Xi1
Attempt to start containers on Xi1. Containers should start without error, and the localtime plugin in the config.json should look as follows:
```json
"localtime":{
"required":false,
"data":{}
}
```
> Fix invalid data for Local Time rdk plugin

- AppInfrastructure/Common/CMakeLists.txt
- AppInfrastructure/IpcService/CMakeLists.txt
This added an absolute path in DobbyTargets.cmake, causing issues
when using sstate for building downstream consumers.
Attempt to build a consumer component such as `Thunder` or `rdkServices` with Dobby coming from an sstate cache. If build succeeds without failure, the test has succeeded.
> Make boost include dirs private in targets using it

- rdkPlugins/Networking/source/MulticastForwarder.cpp
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
Add a check in MulticastForwarder to check compatibility when removing rules. Previously only checked compatibility when adding the rules.
Start/stop a container when `smcroute` isn't installed. Without the patch, you will see the following error in DobbyDaemon when stopping the container:
```
sh: 1: /usr/sbin/smcroutectl: not found
sh: 1: /usr/sbin/smcroutectl: not found
Sorry, rule does not exist.
```
With the patch, you will see a nicer error:
```
Multicast forwarding not supported - smcroutectl not found in PATH (2 - No such file or directory)
```
> Check compatiblity when removing multicast forwarder rules in postHalt

- rdkPlugins/Networking/source/MulticastForwarder.cpp
Multicast forwarder should forward packets sent on the localhost interface to `dobby0`. 
This is necessary for rtRemote which uses the localhost to send multicast packets between processes on a single host.
Same test procedure as per https://github.com/rdkcentral/Dobby/pull/63. The `lo` interface should also be added to the smcroute.conf file:
```
mroute from lo group 224.10.0.12 to dobby0
```
> Enable multicast forwarding on localhost

- rdkPlugins/Storage/source/LoopMountDetails.cpp
Fix issue where Storage plugin would fail to mount the img file when using a deeply nested path as the destination
Create a loopback mount with the following config:
```
"loopback": [
{
"destination": "/home/private/test/long/path",
"flags": 14,
"fstype": "ext4",
"source": "/tmp/data/data.img"
}
]
```
The storage plugin should run successfully. Without this PR a permission denied error will be seen.
> Adjust permissions on created directories for storage plugin

- CMakeLists.txt
- README.md
- bundle/lib/source/DobbyConfig.cpp
- pluginLauncher/lib/include/IDobbyRdkPlugin.h
- pluginLauncher/lib/source/DobbyRdkPluginManager.cpp
- pluginLauncher/tool/source/Main.cpp
- rdkPlugins/Common/include/DobbyLoggerBase.h
- rdkPlugins/Common/include/RdkPluginBase.h
- rdkPlugins/TestPlugin/source/TestRdkPlugin.cpp
- rdkPlugins/TestPlugin/source/TestRdkPlugin.h
The StartContainer hook is not used by any existing plugins and causes issues with library dependencies inside containers.
Disable the hook by default, but allow manually enabling it with a CMake flag if desired.
Whilst this does not break any existing plugin behaviour, this is a **breaking change** as the currently documented behaviour for plugin hooks is changed.
Build Dobby as normal. The `startContainer` hook should not run when starting a container and the `startContainer` section should not be populated in the container config after starting a container.
Setting `-DUSE_STARTCONTAINER_HOOK=ON` when compiling Dobby should revert this behaviour and the startContainer hook should run
> Allow enabling/disabling the start container hook

- rdkPlugins/Networking/source/MulticastForwarder.cpp
Ensure the smcroute config file is closed and fully written to before attempting to reload smcroute to prevent smcroute restarting before the file is written.
Ensure smcroute always loads the config file correctly.
> [RDK-3029] Ensure smcroute config file is closed properly

- bundle/lib/include/DobbyConfig.h
- bundle/lib/source/DobbyConfig.cpp
Always set the hostname of the container to the container ID
Start a container from the same bundle multiple times, each with a different ID. The hostname of the container should always match the ID
> Always set the container hostname to container ID

- bundle/lib/include/DobbyRootfs.h
- bundle/lib/source/DobbyRootfs.cpp
- rdkPlugins/Storage/source/LoopMountDetails.cpp
There was an issue where container was created and not run, it was resulting in temp mount being left because cleaning up was done in post start hook, which wasn't run as container wasn't start.
Fixed by checking if cleaning was done on post stop hook which should be run all the times.
This ticket is fix for problem found while doing RDK-30291.
Create container with storage plugin on, but without "post start" hook. It shouldn't left mount to `directory.temp`.
> RDK-30291 Fixed occasional temp mounts

- develop/vagrant/Vagrantfile
During the Vagrant VM setup, the figlet package `apt install` was executed before the `apt update`. `Apt` couldn't find the package and the VM setup aborted.
`apt update` is now executed before the figlet `apt install`.
Try to set up a new Vagrant VM (`vagrant up`).
> Initialize apt before installing packages during Vagrant VM setup.

- CMakeLists.txt
- pluginLauncher/tool/source/Main.cpp
Fixed build switch logic for DobbyTool,
corrected hook point name letter casing in the pluginLauncher.
Check if DobbyTool is actually compiled in a debug build,
test if the pluginLauncher actually runs the preCreation hook.
> Little fixes for two tools

- AppInfrastructure/Public/Dobby/IDobbyProxy.h
- bundle/lib/include/DobbyConfig.h
- bundle/lib/source/DobbyConfig.cpp
- client/lib/include/DobbyProxy.h
- client/lib/source/DobbyProxy.cpp
- client/tool/source/Main.cpp
- daemon/lib/source/Dobby.cpp
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyManager.h
Allow the user to add additional environment variables dynamically when starting a container.
Change is necessary to allow setting `PX_WAYLAND_CLIENT_REMOTE_OBJECT_NAME` when starting a container for rdkbrowser2
`DobbyTool start` command has new `--envvar` argument that can add environment variables. Argument can be repeated to add multiple environment variables. Example:
```
DobbyTool start --envvar "FOO=bar" --envvar "BAR=thing" sleep ./sleepybundle/ env
```
Can also be tested with OCIContainer Thunder Plugin with https://github.com/rdkcentral/rdkservices/pull/801
> Allow setting environment variable(s) when starting container

- bundle/lib/source/DobbyConfig.cpp
XDG_RUNTIME_DIR was not set when adding westeros socket during container startup
Add westeros socket using DobbyTool/OCIContainer when starting container. `XDG_RUNTIME_DIR` should be set to `/tmp` inside the container
> Fix XDG_RUNTIME_DIR not set

- bundle/lib/source/DobbySpecConfig.cpp
When rewriting arrays from Dobby plugin specs to OCI plugin specs, source array was iterated over wrong elements, append was tried on the destination array even if it didn't exist. This resulted in invalid data being written to the OCI plugin spec.
Prepare a Dobby plugin spec which contains a non-empty array, run it through DobbyBundleGenerator and check the output config file.
> Fix writing arrays to OCI plugin specs

- bundle/lib/source/DobbySpecConfig.cpp
- bundle/lib/source/templates/OciConfigJson1.0.2-dobby.template
- bundle/lib/source/templates/OciConfigJsonVM1.0.2-dobby.template
- bundle/runtime-schemas/defs-plugins.json
- pluginLauncher/lib/CMakeLists.txt
- pluginLauncher/lib/include/DobbyRdkPluginDependencySolver.h
- pluginLauncher/lib/include/DobbyRdkPluginManager.h
- pluginLauncher/lib/include/IDobbyRdkPlugin.h
- pluginLauncher/lib/source/DobbyRdkPluginDependencySolver.cpp
- pluginLauncher/lib/source/DobbyRdkPluginManager.cpp
- rdkPlugins/Common/include/DobbyLoggerBase.h
- rdkPlugins/Common/include/RdkPluginBase.h
- rdkPlugins/GPU/source/GpuPlugin.cpp
- rdkPlugins/GPU/source/GpuPlugin.h
- rdkPlugins/HttpProxy/source/HttpProxyPlugin.cpp
- rdkPlugins/HttpProxy/source/HttpProxyPlugin.h
- rdkPlugins/IPC/source/IpcPlugin.cpp
- rdkPlugins/IPC/source/IpcPlugin.h
- rdkPlugins/LocalTime/source/LocalTimePlugin.cpp
- rdkPlugins/LocalTime/source/LocalTimePlugin.h
- rdkPlugins/Logging/source/LoggingPlugin.cpp
- rdkPlugins/Logging/source/LoggingPlugin.h
- rdkPlugins/Networking/include/NetworkingPlugin.h
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
- rdkPlugins/RtScheduling/source/RtSchedulingPlugin.cpp
- rdkPlugins/RtScheduling/source/RtSchedulingPlugin.h
- rdkPlugins/Storage/source/Storage.cpp
- rdkPlugins/Storage/source/Storage.h
- rdkPlugins/TestPlugin/source/TestRdkPlugin.cpp
- rdkPlugins/TestPlugin/source/TestRdkPlugin.h
DobbyRdkPluginManager now processes RDK plugins for a given hook according to the order of plugin dependency. 
Before this change, RDK plugins were processed according to the order in which they are declared in the "RdkPlugins" section of the "defs-plugins" schema file. This can result in hook execution failures when plugin A which depends on plugin B is processed before plugin B. 
After the change, if plugin A depends on plugin B, hooks for plugin B will be run before hooks for plugin A.
This is inverted (A before B) for postHalt and postStop so that the plugins on which other plugins depend are shut down later.
The dependencies can be defined in the container spec. Each plugin spec now contains a "dependsOn" array.
If, for example, plugin A depends on plugins B and C, then plugin A's …
> Run plugin hooks in order determined by dependencies

- AppInfrastructure/Logging/source/Logging.cpp
- bundle/lib/source/DobbyTemplate.cpp
- cmake/Finddbus.cmake
- cmake/Findjsoncpp.cmake
- daemon/lib/source/DobbyWorkQueue.h
- rdkPlugins/Networking/source/Netfilter.cpp
- rdkPlugins/Storage/source/StorageHelper.cpp
- utils/source/DobbyTimer.h
Fix errors when compiling Dobby on Ubuntu 20.04 with GCC10
Build Dobby on the following platforms, all should succeed without error:
* Vagrant (Ubuntu 16.04 w/ GCC 6.4)
* Bitbake
* Ubuntu 20.04 w/ GCC 10.2
> Fix compiler errors on gcc10

- bundle/lib/include/DobbyRootfs.h
- bundle/lib/source/DobbyRootfs.cpp
- rdkPlugins/Logging/source/LoggingPlugin.cpp
Stop Dobby leaking file descriptors.
The logging plugin and `DobbyRootfs` were not correctly closing open fds when containers exited, meaning the amount of fds in use by Dobby would increase by 2 each time a container was launched and stopped.
Run DobbyDaemon with the following valgrind command:
```
sudo valgrind --tool=memcheck --tool=callgrind --track-fds=yes DobbyDaemon -v --nofork
```
Launch and stop a number of containers repeatedly then close the daemon with Ctrl+C.
With the PR applied, Dobby should always exit with 11 open fds.
```
==30666== FILE DESCRIPTORS: 11 open at exit.
```
Without the PR, this number would increase by 2 for each container launched.
> Fix leaking file descriptors

- bundle/lib/source/templates/OciConfigJson1.0.2-dobby.template
- rdkPlugins/Networking/include/NetworkSetup.h
- rdkPlugins/Networking/source/NetworkSetup.cpp
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
The /sys mount was conditionally compiled out of the OCI config template
and then added by the Networking plugin if network namespacing was enabled.
Because of that, the /sys mount was appended to the end of the mounts array
and processed after the /sys/fs/cgroup mount. As a result, the /sys/fs/cgroup
mount was failing.
Remove the conditional include of the /sys mount from the template and
the mount logic from the Networking plugin. The mount is now always added
in the proper place of the mount config array, i.e. before the /sys/fs/cgroup
mount.
Create a container with a cgroup mount defined in the config, check if the cgroup
directory is visible in the container's file system.
> Always add /sys mount

- CMakeLists.txt
- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/GPU/README.md
- rdkPlugins/GPU/source/GpuPlugin.cpp
- rdkPlugins/IONMemory/CMakeLists.txt
- rdkPlugins/IONMemory/README.md
- rdkPlugins/IONMemory/source/IonMemoryPlugin.cpp
- rdkPlugins/IONMemory/source/IonMemoryPlugin.h
Add ION Memory limiting plugin to allow containers to control ION heap limits.
Also removes the bind mount that was used to fix the cgroup mount point as this is no longer needed in crun (see https://github.com/containers/crun/issues/625)
Build with `PLUGIN_IONMEMORY=ON`. IonMemory plugin should be installed. See README.md for more details on config syntax.
When starting container, ION memory limits should be set:
```
0000003010.263200 NFO: < M:IonMemoryPlugin.cpp F:findIonCGroupMountPoint L:221 > found ION cgroup mounted @ '/sys/fs/cgroup/ion'
0000003010.264158 NFO: < M:IonMemoryPlugin.cpp F:setupContainerIonLimits L:331 > setting ion heap 'Media' limit to 0 for container 'ion'
0000003010.264260 NFO: < M:IonMemoryPlugin.cpp F:setupContainerIonLimits L:331 > setting ion heap 'System' …
```
> RDK-32028: Add ION Memory Plugin

- bundle/lib/source/DobbySpecConfig.cpp
- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/Storage/README.md
- rdkPlugins/Storage/source/LoopMountDetails.cpp
- rdkPlugins/Storage/source/LoopMountDetails.h
- rdkPlugins/Storage/source/Storage.cpp
Add option to disable image management for loopback file system mounts. 
This is needed on Sky builds where the fs images are managed by appsserviced.
Build and run on a sky build, you should no longer see the following error in the log:
```
xattr missing on data file, re-generating a new one
```
And the supplied loopback image file should be used as it.
> NGDEV-180377: Erasing loopback storage on container start

- daemon/process/settings/dobby.xi1.json
Remove `ENABLE_MEDIAINFO=0` from XiOne containers launched from dobby specs
Ensure `get_avstatus.sh` returns valid data when run inside a container
> XIONE-2953: Update Xi1 config file

- daemon/lib/source/DobbyManager.cpp
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
When returning the list of network interfaces to the networking plugin, only return interfaces that are actually available. Log warnings/errors if network interfaces we expect are missing
Edit the dobby.json file to add a non-existent interface:
```
"network": {
"externalInterfaces": [ "enp0s8", "enp0s3", "fakeiface" ],
"addressRange": "100.64.11.0"
}
```
When starting a container in NAT network mode, a warning will be logged but the container will still start:
```
0000010356.230847 NFO: < M:Dobby.cpp F:getExtIfaces L:1866 > GetExternalInterfaces()
0000010356.230953 WRN: < M:DobbyManager.cpp F:getExtIfaces L:1705 > Interface 'fakeiface' from settings file not available
```
If none of the interfaces in the settings file are present, an error will be logged and the container will fail to …
> Check if network interfaces are actually available

- .github/workflows/build.yml
Create a GitHub action to automatically build Dobby in various configurations on every PR/push.
Builds Dobby with all optional plugins enabled, with LEGACY_COMPONENTS enabled & disabled for both Debug and Release builds.
This will help to prevent broken builds from being merged into the master branch.
Tested with act: https://github.com/nektos/act.
> Add GitHub action to build Dobby on PRs

- daemon/init/CMakeLists.txt
Fix CMake issue preventing DobbyInit from building when LEGACY_COMPONENTS=OFF due to incorrect ethanlog dependency
Build Dobby with LEGACY_COMPONENTS=OFF
> Fix build error in DobbyInit due to Ethanlog

- bundle/lib/source/DobbySpecConfig.cpp
When launching a container from a Dobby spec, if the spec does not contain an `rtPriority` field, add the rtScheduling plugin regardless with the defaults. This will ensure the process will run in RR scheduling mode. 
This is done to ensure consistency between skyDobby and RDK Dobby, where skyDobby configures the RT scheduling in a syshook
Launch a container from a dobby spec.
If the spec is missing the `rtPriority` field, the `rtScheduling` plugin should be added to the config with no data section. The plugin will use its default value(s):
```
"rtscheduling": {
"required": false,
"data": {}
}
```
The container will run in RR scheduling mode:
```
$ ps -cTeFl | grep sleep
4 S vagrant   3714  3714  3686 RR   46 -  4389 -        676   2 13:07 pts/0    00:00:00 /usr/libexec/DobbyInit sleep 60 …
```
> Always add rtScheduling plugin when launching from Dobby spec

- bundle/lib/source/DobbySpecConfig.cpp
When launched from a dobby spec, containers should not be allowed to adjust their priority, unless the `rtPriority` field is set in the spec (and the `rtScheduling` plugin is therefore added).
This reverts https://github.com/rdkcentral/Dobby/pull/101
See XIONE-3077. 
If the dobby spec has no `rtPriority` field, then the container should have a hard & soft limit of 0 for the RTPRIO rlimit.
> XIONE-3077: Prevent containers from adjusting their priority

- CMakeLists.txt
- plugins/MulticastSockets/CMakeLists.txt
- plugins/MulticastSockets/source/MulticastSocketsPlugin.cpp
- plugins/MulticastSockets/source/MulticastSocketsPlugin.h
Adds the MulticastSockets legacy plugin from skyDobby.
This is added directly as a legacy plugin instead of porting to an RDK plugin as this plugin is not currently necessary outside of Sky platforms. Future work could be undertaken to migrate this to an RDK plugin if necessary.
> RDK-32484/NGDEV-178770: Add MulticastSockets legacy plugin

- bundle/lib/source/DobbyConfig.cpp
Fix a segfault that occurs when launching an OCI config with type `1.0.2-dobby` and no rdkplugins section, 
Create config.json with schema type `1.0.2-dobby` and no rdkplugins section. No segfault should occur.
> Fix segfault when no rdkplugins section in config

- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/AppServices/source/AppServicesRdkPlugin.cpp
- rdkPlugins/AppServices/source/AppServicesRdkPlugin.h
- rdkPlugins/Networking/README.md
- rdkPlugins/Networking/include/NetworkingPlugin.h
- rdkPlugins/Networking/include/PortForwarding.h
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
- rdkPlugins/Networking/source/PortForwarding.cpp
Adds a new option `localhostMasquerade` to the Networking plugin.
If enabled, redirect packets sent to localhost in the container to the host's localhost (via the dobby bridge device) for the forwarded ports.
This allows containers to access services on the host without needing to change existing code to point to the bridge IP address.
This can obviously only work for ports specified in the `containerToHost` section.
Start a server on the host machine running on port 8080. Configure the container to forward the port the server is running on into the container and enable `localhostMasquerade`:
```json
"portForwarding": {
"localhostMasquerade": true,
"containerToHost": [
{
"port": 8080,
"protocol": "tcp"
}
]
}
```
Requests made to `localhost:8080` inside the container will be sent to the …
> Add localhost masquerade feature to Networking plugin

- daemon/process/settings/dobby.xi1.json
Add /dev/fwsocket node to dobby settings file for Xi1 for MS12 support
See JIRA:
- https://ccp.sys.comcast.net/browse/XIONE-3649
- https://ccp.sys.comcast.net/browse/XIONE-2953
- https://ccp.sys.comcast.net/browse/REALTEK-379
> XIONE-2953: Add /dev/fwsocket node for Xi1

- CMakeLists.txt
- daemon/process/settings/dobby.xi1.json
- settings/include/Settings.h
- settings/source/Settings.cpp
Add a new cmake option: `-DREGION`. Valid options include `NONE` (Default), `UK`, `IT` and `DE`. 
In the dobby settings file, mounts in the `extraMounts` section(s) can be excluded for certain regions. Add exclusion for the `/dev/fwsocket` socket for UK Xi1 builds.
See JIRA ticket. `/dev/fwsocket` should not be mounted on UK region builds.
> XIONE-3649: Add build region CMake option

- rdkPlugins/AppServices/source/AppServicesRdkPlugin.cpp
- rdkPlugins/AppServices/source/AppServicesRdkPlugin.h
- rdkPlugins/Networking/include/NetworkingPlugin.h
- rdkPlugins/Networking/include/PortForwarding.h
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
- rdkPlugins/Networking/source/PortForwarding.cpp
For both the Networking and AS plugins, move the localhost masquerade code to the createRuntime hook.
The localhost masquerade code should run in the container namespace. However, whilst using the createContainer hook for this worked fine on the VM, on some STBs it fails with permissions issues:
```
0000000181.918440 NFO: < M:DobbyRdkPluginManager.cpp F:runPlugins L:714 > Running appservicesrdk plugin
0000000181.928768 ERR: < M:Netfilter.cpp F:forkExec L:281 > /usr/sbin/iptables-restore failed with exit code 2
0000000181.928830 ERR: < M:Netfilter.cpp F:dumpPipeContents L:137 > iptables-restore v1.6.0: iptables-restore: unable to initialize table 'nat'
Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
0000000181.928939 ERR: < …
```
> Use createRuntime hook for localhost masquerade

- rdkPlugins/AppServices/source/AppServicesRdkPlugin.cpp
- rdkPlugins/Networking/include/TapInterface.h
- rdkPlugins/Networking/source/NetworkSetup.cpp
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
- rdkPlugins/Networking/source/PortForwarding.cpp
- rdkPlugins/Networking/source/TapInterface.cpp
- rdkPlugins/Thunder/source/ThunderPlugin.cpp
Few bug fixes for networking plugin & localhost masquerade:
* Ensure localhost masquerade is only enabled when set to `true` in config
* Fix IPv6 support for localhost masquerade
* Remove unnecessary logging
* Reduce unnecessary errors on platforms without tap/tun support
Ensure containers launch without errors on all platforms
> Bug fixes for localhost masquerade and networking plugin

- bundle/lib/source/templates/OciConfigJson1.0.2-dobby.template
- daemon/process/settings/dobby.xi1.json
- Open container for SVP playback on Realtek SoC
- Enabling SVP by adding extra env will be in separate commit
- Permissions to needed /opt/drm access will be part of widget config.
See JIRA
- [] New feature (non-breaking change which adds functionality)
> XIONE-4157: Enable SVP for Realtek

- plugins/OpenCDM/source/OpenCDMPlugin.cpp
Description
XIONE-4157
Open container for SVP playback on Realtek SoC
Enabling SVP by adding extra env will be in separate commit
For SVP playback sockets are created from app context therefore OCDM directory need group write permission so it can be written and use by any member of Apps group.
Test Procedure
See JIRA
Type of Change
Bug fix (non-breaking change which fixes an issue)
[] New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
Other (doesn't fit into the above categories - e.g. documentation updates)
Requires Bitbake Recipe changes?
The base Bitbake recipe (meta-rdk-ext/recipes-containers/dobby/dobby.bb) must be modified to support the changes in this PR (beyond updating …
> Add write access to OCDM directory so svp-sockets could be created

- rdkPlugins/Storage/source/ImageManager.cpp
- rdkPlugins/Storage/source/ImageManager.h
- rdkPlugins/Storage/source/Storage.cpp
- rdkPlugins/Storage/source/StorageHelper.cpp
Adds possibility to loop mount xfs filesystem (in storage plugin).
Define storage plugin entry in config.json file with xfs loop mount:
_"storage": {
"required": true,
"data": {
"loopback": [
{
"destination": "/home/private",
"flags": 14,
"fstype": "xfs",
"source": "/tmp/data.img"
}
]
}
}_
> Allow to loop mount xfs file system.

- rdkPlugins/Networking/source/NetworkingPlugin.cpp
Prevent the networking plugin generating an invalid dbus service name and failing to connect to dbus with the following error after stopping/starting containers many times:
```
Jun 25 10:32:15 arrisxi6 DobbyDaemon[1896]: failed to register service name 'org.rdk.dobby.plugin.networking.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid1896.pid189
```
Using dbus-monitor. ensure the networking plugin name does not repeatedly append the PID to the end when connecting to dbus
> Fix invalid dbus service name in Networking Plugin

- daemon/lib/source/DobbyRunC.cpp
Change the crun logfile location to `/opt/logs` to ensure it's stored with the rest of the RDK logfiles.
Ensure `/opt/logs/crun.log` is created when starting containers.
> Change crun logfile path to /opt/logs

- rdkPlugins/LocalTime/source/LocalTimePlugin.cpp
Localtime plugin should correctly null-terminate the filename, preventing the following issue:
```
ls -lah /proc/12345/root/etc/
drwxr-xr-x    3 root     root         220 Jul 28 12:33 .
drwxr-xr-x   15 root     root         300 Jul 28 12:33 ..
lrwxrwxrwx    1 root     root          36 Jul 28 12:33 localtime -> /usr/share/zoneinfo/Europe/London???
```
Ensure localtime plugin correctly creates a valid symlink.
> Fix null termination in localtime

- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyStats.cpp
- daemon/lib/source/DobbyStats.h
Return more info about the running processes inside a container.
Will return an array containing all the processes running inside the container, in additional to the existing PID array:
```json
"processes" : 
[
{
"cmdline" : "/usr/libexec/DobbyInit /echo_test.sh ",
"executable" : "/usr/local/libexec/DobbyInit",
"nsPid" : 1,
"pid" : 17263
},
{
"cmdline" : "/bin/bash /echo_test.sh ",
"executable" : "/bin/bash",
"nsPid" : 5,
"pid" : 17326
},
{
"cmdline" : "sleep 1 ",
"executable" : "/bin/sleep",
"nsPid" : 6,
"pid" : 17327
}
]
```
Also remove deprecated `FastWriter` jsoncpp call.
Start container. Run `DobbyTool info <id>`. Check output of processes array matches `ps auxf` output.
> Add more process information to container info

- bundle/lib/source/DobbyRootfs.cpp
- daemon/lib/include/Dobby.h
- daemon/lib/include/DobbyLogger.h
- daemon/lib/source/Dobby.cpp
- daemon/lib/source/DobbyLogger.cpp
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyManager.h
- pluginLauncher/lib/include/IDobbyRdkLoggingPlugin.h
- pluginLauncher/lib/source/DobbyRdkPluginManager.cpp
- rdkPlugins/Logging/source/LoggingPlugin.cpp
- rdkPlugins/Logging/source/LoggingPlugin.h
- rdkPlugins/Networking/source/StdStreamPipe.cpp
In some scenarios, DobbyDaemon can segfault during daemon shutdown (whether shutdown is triggered by systemd or the admin.shutdown command over dbus).
Segfault occurs when a container is writing large amounts of log data whilst the container is shutting down. Due to a race condition Dobby can attempt to unload the logging plugin whilst the deamon is still writing logs, causing segfault.
PR makes the following improvements:
* Send cancellation request to logging threads during daemon shutdown to ensure logging finishes cleanly
* Prevent unloading plugin `.so` if a reference is still held (this ideally should never happen but until the root cause of the race condition can be identified this prevents the daemon from crashing entirely)
* Fix warnings and memory leaks reported by Valgrind
* …
> LLAMA-3127: Prevent segfault at shutdown

- daemon/process/source/Main.cpp
Increase the default log level of Debug builds from Milestone to Info.
Debug builds should print `NFO` log messages by default
> Increase default log level in debug builds

- daemon/process/dobby.service.in
Increase Dobby watchdog timeout to 10 seconds
> XIONE-6161: Increase watchdog timeout

- rdkPlugins/Networking/source/Netfilter.cpp
Prevent segfault when checking for duplicate iptables rules
See ticket
> LLAMA-3448: Additional sanity check in trimDuplicates

- pluginLauncher/tool/CMakeLists.txt
- pluginLauncher/tool/exported.syms
- pluginLauncher/tool/source/Main.cpp
- rdkPlugins/Logging/source/LoggingPlugin.cpp
Send the log output from DobbyPluginLauncher to journald as well as stdout.
On Sky builds, the container stdout is sent to the console.log file, which is not captured as part of the standard log collection. By sending plugin output to journald, it will end up in dobby's logfile inline with the rest of the Dobby and container output (handled by ethanlog)
This will make debugging plugin issues easier
* Start container
* Ensure log messages from the createRuntime, createContainer, poststart and poststop should be seen in journald
Example
```
Sep 24 11:15:05 dobby-vagrant-focal test[28789]: Running hook poststart for container 'test'
Sep 24 11:15:05 dobby-vagrant-focal test[28789]: Loaded plugin 'ipc' from '/usr/lib/plugins/dobby/libIpcPlugin.so.1'
Sep 24 11:15:05 dobby-vagrant-focal …
```
> Send plugin log output to journald

- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/Thunder/README.md
- rdkPlugins/Thunder/source/ThunderPlugin.cpp
- rdkPlugins/Thunder/source/ThunderPlugin.h
Some applications should be allowed to generate their own tokens instead of relying on the pre-generated token from Dobby.
This is required for applications such as web browsers where the single container configuration can be reused for many different applications, each requiring a unique token.
Create a container with Thunder plugin and set `trusted: true`.
The container should have a bind-mount for the security agent socket, and should be able to generate it's own token.
> RDK-34228: Trusted apps can generate their own tokens

- daemon/lib/source/DobbyRunC.cpp
We shouldn't do waitpid if fork failed, as if there was another child it will result in infinite wait. Also why do we even use waitpid at all? In forkExecRunC there is implementation based on vfork which is blocking by definition. Which should mean that if we got to this line we already finished the child process. I guess it wouldn't harm (at least as long as we check if it succeed to fork on the first place).
We would somehow need to fail the fork, while having other child process. Only disabling fork at all would get "10 - No child processes" result.
> XIONE-6236 Don't wait for failed forks

- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyRunC.cpp
- daemon/lib/source/DobbyRunC.h
We need to make sure RuncCreate doesn't stuck. We need to add timeout in case this process take too long and kill it if needed.
Change timeout to 80000 ms (so it will sometime destroy creation in the middle) and check if next run will be successful (assuming no timeout occurred).
> XIONE-6236 Create timeout for RuncCreate

- daemon/lib/source/Dobby.cpp
Created high priority wagging thread for Dobby, which will work even if CPU resources are scarce. It has a downside of not reflecting true Dobby state, but this is required during boot-up as sometimes Dobby gets killed by watchdog due to other processes taking to much CPU. This solution is a workaround and should be disabled when real offenders are found.
Force box to be out of CPU for more than 10 seconds (watchdog timeout) and running `systemctl status Dobby` should show if Dobby restarted. Without this fix there is 24% chance to dobby to be restarted. With this fix during the first 120 seconds (defined by `HIGH_USAGE_TIME_SEC`) there should be not restart due to high CPU usage. For testing one can set this define to something very big (I used 3600 just so I can make a lot of tests).
> XIONE-6749 Created high priority watchdog wagger

- daemon/lib/source/DobbyLogger.cpp
- rdkPlugins/Logging/source/LoggingPlugin.cpp
- rdkPlugins/Logging/source/LoggingPlugin.h
Prevent Dobby from locking up and using excessive CPU when printing very long log messages to journald.
This only impacts the journald log sink, logging to files was not affected by this issue
Create test container that prints a very long single line (>8000 chars) and configure logging plugin to use journald.
Log message should be printed to journald without error. Note very, very long messages max be broken up into multiple lines based on the journal's LineMax setting
> RDKTV-12390: Handle long container log lines better with  journald

- daemon/lib/source/DobbyRunC.cpp
If timeout occur we should kill whole group, not only parent process. Sadly it will not help if other sessions are created, but it is better than previous solution.
Change timeout to 80000 ms (so it will sometime destroy creation in the middle) and check if timeout occurred process group was killed properly.
> XIONE-6236 Kill CrunCreate group instead of only process

- pluginLauncher/lib/include/DobbyRdkPluginManager.h
- pluginLauncher/lib/source/DobbyRdkPluginManager.cpp
Added timeout for hook execution in plugin launcher because it looks like some plugins freezes. With additional log provided by this commit we should be able to pinpoint the offender.
Modify any plugin to have some long (more than 4 seconds) wait in it. This should make timeout happen and if plugin is required then container will fail to start.
> XIONE-7154 Plugin launcher hook execution timeout

- daemon/lib/source/DobbyManager.cpp
- pluginLauncher/lib/include/DobbyRdkPluginManager.h
- pluginLauncher/lib/source/DobbyRdkPluginManager.cpp
- pluginLauncher/tool/source/Main.cpp
Added timeout for hook execution in plugin launcher because it looks like some plugins freezes. With additional log provided by this commit we should be able to pinpoint the offender.
This is continuation of https://github.com/rdkcentral/Dobby/pull/159 which needed to be reverted due to the fact that not every hookpoint should be run with timeout.
Modify any plugin to have some long (more than 4 seconds) wait in it. This should make timeout happen and if plugin is required then container will fail to start.
> XIONE-7154/XIONE-7465: Plugin launcher hook execution timeout - improved

- AppInfrastructure/Common/include/IPollLoop.h
- AppInfrastructure/Common/include/PollLoop.h
- AppInfrastructure/Common/source/PollLoop.cpp
- AppInfrastructure/ReadLine/source/ReadLine.cpp
- AppInfrastructure/ReadLine/source/ReadLine.h
- daemon/lib/CMakeLists.txt
- daemon/lib/source/DobbyLogRelay.cpp
- daemon/lib/source/DobbyLogRelay.h
- daemon/lib/source/DobbyLogger.cpp
- daemon/lib/source/DobbyLogger.h
- daemon/lib/source/DobbyManager.cpp
- daemon/process/settings/dobby.dev_vm.json
- pluginLauncher/lib/include/IDobbyRdkLoggingPlugin.h
- rdkPlugins/Logging/CMakeLists.txt
- rdkPlugins/Logging/LogRelay.md
- rdkPlugins/Logging/include/ILoggingSink.h
- rdkPlugins/Logging/source/FileSink.cpp
- rdkPlugins/Logging/source/FileSink.h
- rdkPlugins/Logging/source/JournaldSink.cpp
- rdkPlugins/Logging/source/JournaldSink.h
- rdkPlugins/Logging/source/LoggingPlugin.cpp
- rdkPlugins/Logging/source/LoggingPlugin.h
- rdkPlugins/Logging/source/NullSink.cpp
- rdkPlugins/Logging/source/NullSink.h
- settings/include/IDobbySettings.h
- settings/include/Settings.h
- settings/source/Settings.cpp
When containers attempt to log directly to journald (e.g. `sd_journal_print()`) or syslog, the log messages may not correctly appear in journald.
After adding `/run/systemd/journal/socket` into a container that directly calls `sd_journal_print`, the log messages are seen in `journalctl -f`. However, these messages are not tagged with a `_SYSTEMD_UNIT` tag. This is because the message unit is determined using the PID of the process, which does not match with a known unit PID when the process runs in a container.
As a result, when filtering the logs by unit (`journalctl -fu dobby`), the messages do not appear. This is an issue with RDK log collection scripts.
This PR makes the following changes:
* Based on the relevant setting in `/etc/dobby.json`, create dobby syslog and journald sockets …
> RDKTV-12717/RDKTV-13079: Support relaying syslog/journald messages

- daemon/lib/source/DobbyContainer.h
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyManager.h
- daemon/lib/source/DobbyRunC.cpp
- daemon/lib/source/DobbyRunC.h
In some scenarios on Xi1, processes can end up in a state where they don't respond to SIGKILL (assumed uninterruptible sleep).
In this case, Dobby may get stuck in a crash loop when attempting to cleanup the container. 
The following logic is introduced:
* At Dobby start, check for leftover containers
* If container is in Running state, attempt to kill with SIGKILL
* If SIGKILL success - delete container
* If SIGKILL fail - mark container as "stuck" and do not attempt to delete
* Add the container to our internal list of running containers in the Unknown state to prevent the container from being restarted
* If container in stopped state, attempt to delete
* If delete fails, then mark container as "stuck"
* If we have any containers marked as "stuck", regularly check if they are still …
> XIONE-7775: Handle containers that don't respond to SIGKILL during cleanup

- daemon/lib/source/DobbyManager.cpp
Ensure we don't break out of the cleanupContainers loop too early.
Fix regression introduced by https://github.com/rdkcentral/Dobby/pull/173
Start multiple containers. Stop DobbyDaemon. Restart DobbyDaemon. All containers should be cleaned up
> XIONE-7775: Fix cleanup loop with multiple containers

- daemon/lib/source/DobbyManager.cpp
- settings/source/Settings.cpp
Fix some spurious error messages seen on STB due to uninitialised variables.
Ensure variables have correct default values instead of whatever randomly gets assigned to them.
Check the following spurious errors aren't present during startup or shutdown
```
failed to find timer with id 1952541797 to remove
```
```
Syslog relay enabled but no socket path set in settings
Journald relay enabled but no socket path set in settings
```
> Fix spurious error messages

- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyManager.h
- pluginLauncher/lib/include/DobbyRdkPluginUtils.h
- pluginLauncher/lib/source/DobbyRdkPluginUtils.cpp
- pluginLauncher/tool/source/Main.cpp
Currently when restarting Dobby, containers are cleaned up but the postHalt plugin is not run. This can result in leftover iptables rules which can cause conflicts when starting new containers.
When Dobby is shut down gracefully, call StopContainer to correctly stop containers.
If containers are detected after a dobby restart (e.g. if daemon did not gracefully shut down, perhaps after a crash), then make a best-effort attempt to run the postHalt hook.
This will impact shutdown/startup performance by 1-2 seconds if many containers were running, but ensures that the device is left in a good state so is worth the impact.
Test both graceful (SIGTERM) and force (SIGKILL) shutdown of Dobby daemon.
* Networking should work correctly when launching the same container after daemon restart
* Dobby …
> LLAMA-5460: Ensure iptables rules are cleaned up after Dobby restart

- AppInfrastructure/IpcService/source/sdbus/SDBusArguments.cpp
- daemon/lib/source/DobbyStartState.cpp
Add missing headers causing build errors on RPi
```
/home/pi/src/Dobby/AppInfrastructure/IpcService/source/sdbus/SDBusArguments.cpp: In member function 'void SDBusVariantVisitor::operator()(const uint8_t&)':
/home/pi/src/Dobby/AppInfrastructure/IpcService/source/sdbus/SDBusArguments.cpp:60:28: error: 'system_error' is not a member of 'std'
60 | throw std::system_error(-rc, std::generic_category()); \
| ^~~~~~~~~~~~
/home/pi/src/Dobby/AppInfrastructure/IpcService/source/sdbus/SDBusArguments.cpp:69:5: note: in expansion of macro 'BASIC_VARIANT_TYPE_OPERATOR'
69 | BASIC_VARIANT_TYPE_OPERATOR(uint8_t, SD_BUS_TYPE_BYTE)
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/src/Dobby/AppInfrastructure/IpcService/source/sdbus/SDBusArguments.cpp:60:51: error: 'generic_category' is not a member of 'std'
60 | …
```
> Fix build errors on RPi

- daemon/lib/source/DobbyManager.cpp
Fix gcc warnings:
```
In file included from /home/vagrant/srcDobby/daemon/lib/source/DobbyManager.cpp:24:
/home/vagrant/srcDobby/daemon/lib/source/DobbyManager.h: In constructor ‘DobbyManager::DobbyManager(const std::shared_ptr<IDobbyEnv>&, const std::shared_ptr<IDobbyUtils_v3>&, const std::shared_ptr<IDobbyIPCUtils>&, const std::shared_ptr<const IDobbySettings>&, const ContainerStartedFunc&, const ContainerStoppedFunc&)’:
/home/vagrant/srcDobby/daemon/lib/source/DobbyManager.h:221:47: warning: ‘DobbyManager::mLegacyPlugins’ will be initialized after [-Wreorder]
221 |     std::unique_ptr<DobbyLegacyPluginManager> mLegacyPlugins;
|                                               ^~~~~~~~~~~~~~
/home/vagrant/srcDobby/daemon/lib/source/DobbyManager.h:217:9: warning:   ‘int …
```
> Fix some Wreorder warnings from gcc

- daemon/process/source/Main.cpp
Remove the duplicated log messages at daemon startup when running Dobby with `--noconsole --journald` arguments
Only one set of settings log messages should appear.
**Before**
```
Mar 16 12:16:54 dobby-vagrant-focal systemd[1]: Starting RDK Dobby (Container) daemon...
Mar 16 12:16:54 dobby-vagrant-focal DobbyDaemon[39850]: 0000009320.882522 <T-39850> NFO: < M:Main.cpp F:createSettings L:260 > parsing settings from file @ '/etc/dobby.json'
Mar 16 12:16:54 dobby-vagrant-focal DobbyDaemon[39850]: parsing settings from file @ '/etc/dobby.json'
Mar 16 12:16:54 dobby-vagrant-focal DobbyDaemon[39850]: 0000009320.884011 <T-39850> NFO: < M:Settings.cpp F:getPathFromEnv L:620 > missing 'AI_WORKSPACE_PATH' environment var, falling back to '/var/volatile/rdk'
Mar 16 12:16:54 dobby-vagrant-focal …
```
> Remove duplicate settings messages at daemon start

- daemon/lib/source/Dobby.cpp
- daemon/process/CMakeLists.txt
- daemon/process/dobby.service
Change Dobby service from `Type=dbus` to `Type=notify` to ensure that systemd does not mark Dobby service as ready too early.
Update service file with following changes:
* Switch to notify service type
* Increase watchdog timeout from 10 seconds -> 30 seconds to help prevent DobbyDaemon being killed during bootup on some platforms
* Add `Before=wpeframework` condition to ensure Dobby starts before Thunder and shuts down afterwards
* Note on platforms without Thunder this will not cause an issue as systemd will just ignore the condition
Ensure systemd reports `Started RDK Dobby (Container) daemon.` only when Dobby is completely ready
> Switch to Type=notify systemd service instead of Type=dbus

- client/tool/source/Main.cpp
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyManager.h
`StartFromSpec()` should correctly add custom arguments, environment variables and westeros sockets provided in config.
Previously whilst the function took those arguments, they were not reflected in the generated config file.
Start container from Dobby spec - should work as normal
```
DobbyTool start sleepy ~/srcDobby/tests/dobby_specs/sleepy.json
```
Now start the same spec with a custom argument
```
DobbyTool start sleepy3 ~/srcDobby/tests/dobby_specs/sleepy.json echo hello
```
The container should run the provided command instead of the argument specified in the spec file (in this case `echo hello`)
> LLAMA-4034: Ensure StartFromSpec() respects runtime customisations

- AppInfrastructure/Logging/include/Logging.h
- AppInfrastructure/Logging/source/Logging.cpp
- daemon/init/source/InitMain.cpp
- daemon/lib/source/DobbyLogRelay.cpp
- daemon/lib/source/DobbyStats.cpp
- plugins/EthanLog/client/cat/ethanlog-cat.cpp
- rdkPlugins/Networking/source/IPAllocator.cpp
- rdkPlugins/Networking/source/Netfilter.cpp
- rdkPlugins/Storage/source/ImageManager.cpp
- rdkPlugins/Storage/source/RefCountFile.cpp
Fix number of build issues seen when building Dobby for musl-based platforms (i.e. PrplOS)
Note there is no nice way to detect if a platform is using the GNU or XSI-compliant version of `strerror_r`, so might need to manually define `HAVE_GNU_STRERROR_R` as `0`.
Dobby should build without errors
> Fix build issues with musl-based platforms

- rdkPlugins/Thunder/source/ThunderPlugin.cpp
- rdkPlugins/Thunder/source/ThunderPlugin.h
Dobby Thunder plugin should not error if container is run in `open` network mode.
Whilst in production containers should use NAT network mode, for debugging it is often useful to use `open` network mode. The Thunder plugin should not attempt to add firewall rules or set THUNDER_ACCESS to the dobby bridge in this scenario
Configure a container with `open` network mode and the Thunder plugin. Container should start without error and should be able to access Thunder
> Thunder plugin should work in open network mode

- bundle/runtime-schemas/add_plugin_tables.py
- cmake/Findlibocispec.cmake
Upgrade libocispec to latest version to bring in bugfixes and support latest OCI runtime spec version
Ensure containers work as normal, and no container config options are lost/mangled during container creation - specifically regarding plugins
> Upgrade libocispec to latest version

- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/Storage/CMakeLists.txt
- rdkPlugins/Storage/README.md
- rdkPlugins/Storage/source/DynamicMountDetails.cpp
- rdkPlugins/Storage/source/DynamicMountDetails.h
- rdkPlugins/Storage/source/LoopMountDetails.cpp
- rdkPlugins/Storage/source/MountProperties.h
- rdkPlugins/Storage/source/Storage.cpp
- rdkPlugins/Storage/source/Storage.h
Extends Storage plugin with dynamic mount functionality to allow bind mounts to be created only if the source exists on the host.
Ensure container config.json contains a storage plugin with one or more dynamic mounts specified as described in the associated README.md file.
> RDKTV-16461: Support for dynamic mounts

- rdkPlugins/Networking/README.md
- rdkPlugins/Networking/source/NetworkSetup.cpp
Added rule for allowing Neighbor Discovery Protocol to be passed
between container and host so IPv6 containers could update
Neigh table.
Create container with only IPv6 support in Networking plugin. Run it, and force any connection i.e. with some curl command from inside container. Then check if running:
` ip -6 neigh`
Will return `REACHABLE` fields or are they  `FAILED`
> RDKTV-16945 IPv6 container fixes

- rdkPlugins/Storage/source/DynamicMountDetails.cpp
When a dynamic mount fails, print the error returned by `mount()` to aid debugging
If dynamic mounts fail, the errno and description should be printed.
> Log errno when dynamic mounts fail

- rdkPlugins/Storage/source/DynamicMountDetails.cpp
- rdkPlugins/Storage/source/DynamicMountDetails.h
- rdkPlugins/Storage/source/Storage.cpp
When creating dynamic/optional mounts the destination path must exist prior to bind mounting.
For file mounts at a newly created paths, it is necessary to first create the file within the container file system so that an inode exists to be mounted over. Otherwise the bind mount will fail when the destination path is targeting a read-only area of the file system.
Create dynamic mounts for directories and files at pre-existing or newly created destination paths.
> RDKTV-17779: Ensure dynamic mount destination path exists

- AppInfrastructure/Common/include/ConditionVariable.h
It seams that 1 in 1'000'000'001 cases the value of tv_nsec was incorrect, as according to the specification it should be between 0-999'999'999, and we were allowing value of 1'000'000'000. I also added some extra log in case we have any more condition variable error in future.
- Not applicable (run 10 billion times and make sure no errors is not feasible)
> RDKTV-19597 Condition variable problem fix

- pluginLauncher/lib/include/DobbyRdkPluginUtils.h
- pluginLauncher/lib/source/DobbyRdkPluginUtils.cpp
- rdkPlugins/Networking/include/Netlink.h
- rdkPlugins/Networking/source/Netlink.cpp
- rdkPlugins/Networking/source/NetworkSetup.cpp
Fixed the race when one container was closed and second was started at the same time. It resulted with situation when container A still held information about some vethX, while container B was already assigning it to itself, so when container A postHaltHook was done it removed all traces of vethX which made container B loose the network.
1. Start any container
2. Copy its network setup to some temp file i.e.
`cp /tmp/dobby/plugin/networking/sleepy /tmp/dobby/plugin/networking/tmp_name`
3. Close original container
4. Start original container again
5. There should be a message:
` Tried to use already taken vethName 'veth0', continue looking`
and container should take next available veth instead
> LLAMA-8016 Fixed race with veth devices

- CMakeLists.txt
- pluginLauncher/lib/include/DobbyRdkPluginUtils.h
- pluginLauncher/lib/source/DobbyRdkPluginUtils.cpp
- rdkPlugins/Networking/include/Netlink.h
- rdkPlugins/Networking/source/Netlink.cpp
- rdkPlugins/Networking/source/NetworkSetup.cpp
update version info in CMakeLists.txt
fix for LLAMA-8016
Regression testing focused on switching between different apps (shutting down and launching containers back to back)
See Jira ticket LLAMA-8016 for details
> increment version to 3.5.2

- bundle/lib/include/DobbyConfig.h
- bundle/lib/source/DobbyConfig.cpp
RDKSEC-68 Added the dobby default apparmor file support in Dobby container
Reason for change:Generic dobby default apparmor profile for all applications in Dobby container (if custom apparmor profile is not present)
Test Procedure: Verify the container application process using apparmor profile.
Risks: None.
> RDKSEC-68 Added the dobby default apparmor file support in Dobby container

- rdkPlugins/Networking/include/PortForwarding.h
- rdkPlugins/Networking/source/PortForwarding.cpp
IPv6 cannot route localnet because it lacks the equivalent of: `/proc/sys/net/ipv4/conf/interface/route_localnet`
So we shouldn't route those packets and REJECT them instead, this will allow apps to use IPv4 based connection. NOTE: this means that IPv6 only containers will not have localhost from the host available (they didn't have earlier, but they hold the packets indefinitely).
Useful links:
https://serverfault.com/questions/646522/port-forward-with-iptables - first answer explains what we do with IPv4 and why it works
https://www.cni.dev/plugins/v0.6/meta/portmap/ - other similar issue that claims that IPv6 routing is impossible.
Also masking all fe80:: based traffic (local link address) from inside container to use `2080:d0bb:1e` based address.
1. Flash this solution on platco box …
> RDKTV-13990 Removed route localnet for IPv6

- rdkPlugins/Networking/source/NetworkSetup.cpp
When "none" is selected as network mode, there should be no outgoing network connection. Previously connection was established now it is not.
1. Create container with network "none"
2. Start container i.e. `DobbyTool start sleepy ./sleepy_bundle`
3. Open sh inside container `crun --root /run/rdk/crun exec --tty <container_name> /bin/bash`
4. Change directory to /tmp `cd /tmp` (otherwise you will get read-only filesystem warning in next step)
5. Try to get resource (without DNS) `wget 185.157.233.196`
Without this fix the wget was successful, now it will be failed.
> RDKTV-20651 Added new drop all rule for none network

- bundle/lib/source/DobbyBundleConfig.cpp
Closing the file after file operations to avoid odd behavior and increased the size of length variable for storing larger values.
1. Open the config file and delete some lines `vi /opt/persistent/rdkservices/ResidentApp/Container/config.json`
2. Reboot.
3. Verify corrupted file is fixed and the deleted lines are auto populated.
> RDKTV-20593 Closing the file 

- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/LocalTime/README.md
- rdkPlugins/LocalTime/source/LocalTimePlugin.cpp
- rdkPlugins/LocalTime/source/LocalTimePlugin.h
Added setTZ param to localTime plugin
Set setTZ param in localTime plugin of sleepy container, check logs if Dobby reads it
> RDKTV-20457: Added setTZ param to localTime plugin

- rdkPlugins/Storage/source/DynamicMountDetails.cpp
Previously we were not checking whether the destination path exists or not in the createContainer hook and the addMount() was called, which eventually fails to add the dynamic mount when the destination path is not present.
Fixed this issue by checking whether destination path already exists, if not then create it and the mount is added.
> RDKTV-21075 : Fixed dynamic mount issue 

- pluginLauncher/tool/source/Main.cpp
Status was read into too small buffer and so parsing failed. Made bigger buffer and added logging to indicate better error for future "too small" buffer.
Problem happened with container that has several extra annotations. They seem to be returned with reading container state and the while state was > 1000 bytes.
Fix can be verified with a container with extra annotations
- only SRCREV
> ONEM-29861 Some DAC apps do not start: fix container state read

- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/LocalTime/README.md
- rdkPlugins/LocalTime/source/LocalTimePlugin.cpp
Added path param to localTime plugin
Set path param in localTime plugin and check in the config.json whether the path is correctly set
>  RDK-41482 : make localtime symlink path configurable

- bundle/runtime-schemas/defs-plugins.json
Since data fields(path and setTZ) in localtime are optional, it is removed from the required field
Check whether data fields in localtime are used whenever they are set, else no error should be seen if no data is provided
> Remove data field as required from localtime

- bundle/lib/source/DobbySpecConfig.cpp
- rdkPlugins/Logging/source/NullSink.cpp
When setting console to null in the Dobby spec, we should still enable the logging plugin. Without it, the container stdout/err fds are not drained and just fill up forever - leading to memory increase over time.
Create a container using a Dobby spec with the console field set to `null`.
Ensure that from the perspective of the container, the stdout/err fds are connected to a ptty instead of a memfd.
```
bash-5.1# ls -alh /proc/1/fd
total 0
dr-x------ 2 root root  0 Jun 13 09:11 .
dr-xr-xr-x 9 root root  0 Jun 13 09:11 ..
lrwx------ 1 root root 64 Jun 13 09:11 0 -> /dev/pts/0
lrwx------ 1 root root 64 Jun 13 09:11 1 -> /dev/pts/0
lrwx------ 1 root root 64 Jun 13 09:11 2 -> /dev/pts/0
```
Ensure container memory does not increase over time as log messages are generated. Ensure no log file …
> LLAMA-11078: Ensure logging plugin is correctly enabled

- bundle/lib/include/DobbyConfig.h
- bundle/lib/source/DobbyConfig.cpp
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/DobbyManager.h
- settings/include/IDobbySettings.h
- settings/include/Settings.h
- settings/source/Settings.cpp
Adds possibility to start container with strace enabled.
List of apps to start with strace enabled and directory in which strace output will be stored can be specified in /etc/dobby.json like this:
"strace": {
"apps": ["sleepy_bundle", "other_app"],
"logsDir": "/tmp/strace"
}
1. Add to /etc/dobby.json
"strace": {
"apps": ["sleepy_bundle", "other_app"],
"logsDir": "/tmp/strace"
}
2. start DobbyDaemon
3. Run sleepy_bundle
4. Check for strace logs in /tmp/strace
- [ x] New feature (non-breaking change which adds functionality)
> Run container with strace

- daemon/process/dobby.service
Added ordering constraint to dbus.service
Restart device, check if dobby is stopped before dbus.
> SERXIONE-1401: Added ordering constraint to dbus.service

- bundle/lib/include/DobbySpecConfig.h
- bundle/lib/source/DobbySpecConfig.cpp
- bundle/lib/source/templates/OciConfigJson1.0.2-dobby.template
- bundle/lib/source/templates/OciConfigJsonVM1.0.2-dobby.template
RDK-42156: Add support for seccomp in spec files.
Run sleepy container using spec file with the following root object added:
"seccomp": {
"defaultAction": "SCMP_ACT_ALLOW",
"syscalls": {
"names": [
"chdir"
],
"action": "SCMP_ACT_ERRNO"
}    	
}
Check /proc/sleepy_pid/status. Seccomp should be set to 2.
> RDK-42156: Add support for seccomp in spec files

- bundle/lib/source/DobbyConfig.cpp
Replaced at one occurance with fopen() as fclose() is used for closing the file
> RDK-42218 Avoid popen system call wherever possible

- daemon/lib/source/DobbyRunC.cpp
Scenario that caused problem:
1. start chocolate-doom DAC app
2. stop the chocolate-doom DAC app
3. repeat step 1-2 until you noticed dbg logging (-vvvv) "SIGTERM kill wasn't kill container (probably masked)"
4. sometimes that last call succeeds, sometimes not and thus an error is returned. Even though the container was in the end successfully killed.
This fix should give more time for the container to reach the ContainerStatus::Stopped state. 
See scenario above
-
> ONEM-32701 Give container more time to stop

- unit_tests/L1_testing/README.md
- unit_tests/L1_testing/mocks/DobbyManagerMock.cpp
- unit_tests/L1_testing/mocks/DobbyManagerMock.h
- unit_tests/L1_testing/mocks/dobbymanager/DobbyManager.h
- unit_tests/L1_testing/tests/DobbyTest/DaemonDobbyTests.cpp
1. Checking whether onContainerStarted callback is triggering when startFromSpec, startFromBundle method calls
2. Checking whether onContainerStopped callback is triggering when stop mehod calls
3. Updated the README.md file
In github workflow L1 test is running and passing
- Enhancing Dobby L1 test
- 
- Not required
> [RDK-45574] Enhancing the L1 Unit Test for Dobby.h

- bundle/lib/include/DobbyConfig.h
- bundle/lib/source/DobbyConfig.cpp
- daemon/lib/source/DobbyManager.cpp
- settings/include/IDobbySettings.h
- settings/include/Settings.h
- settings/source/Settings.cpp
- unit_tests/L1_testing/mocks/DobbyConfig.h
- unit_tests/L1_testing/mocks/DobbyConfigMock.cpp
- unit_tests/L1_testing/mocks/DobbyConfigMock.h
- unit_tests/L1_testing/mocks/DobbySettingsMock.h
- unit_tests/L1_testing/mocks/IDobbySettingsMock.h
- unit_tests/L1_testing/tests/DobbyManagerTest/CMakeLists.txt
- unit_tests/L1_testing/tests/DobbyTest/CMakeLists.txt
RDK-45299: Add Apparmor contol and profile name to the device specific container config
Add to /etc/dobby.json
"apparmor": {
"enabled": true,
"defaultProfile": "dobby_default"
}
Check DobbyDaemon startup logs is /etc/dobby,json was correctly parsed.
Run any container and check if it uses dobby_default apparmor profile.
> RDK-45299: Add Apparmor contol and profile name to the device specific container config

- .github/workflows/build.yml
Remove apt install libgtest-dev in yml file, since we are cloning and installing the Googletest in Install gmock step.
In github workflow L1 test is running and passing
- Enhancing Dobby L1 test
- Not required
> Remove apt install libgtest-dev in yml file

- bundle/lib/include/DobbyConfig.h
- bundle/lib/source/DobbyConfig.cpp
- daemon/lib/source/DobbyManager.cpp
- settings/include/IDobbySettings.h
- settings/include/Settings.h
- settings/source/Settings.cpp
- unit_tests/L1_testing/mocks/DobbyConfig.h
- unit_tests/L1_testing/mocks/DobbyConfigMock.cpp
- unit_tests/L1_testing/mocks/DobbyConfigMock.h
- unit_tests/L1_testing/mocks/DobbySettingsMock.h
RDKTV-17990: Setting pids cgroup limit
In /etc/dobby.json add 
"pids": {
"enable": true,
"limit":100
}
Restart Dobby, start an application and check /sys/fs/cgroup/pids/<app_name>/pids.max.
> RDKTV-17990: Setting pids cgroup limit

- unit_tests/L1_testing/tests/DobbyManagerTest/DaemonDobbyManagerTest.cpp
L1 test cases are added for ociConfigOfContainer and specOfContainer apis in Dobby master branch.
**UseCases**:
1. ociConfigOfContainer_Success
2. ociConfigOfContainer_FailedToFindContainer
3. ociConfigOfContainer_EmptyOCIConfigJsonSpec
4. specOfContainer_FailedToFindContainer
5. specOfContainer_SuccessWhenStarting
6. specOfContainer_EmptyJsonSpec
Run ./guthub/workflows/build.yml file. All unit tests should pass.
No
> RDK-45967 - Added L1 test cases for ociConfigOfContainer Api.

- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/include/DobbyManager.h
- unit_tests/L1_testing/tests/DobbyManagerTest/DaemonDobbyManagerTest.cpp
https://ccp.sys.comcast.net/browse/DELIA-64149
pthread_kill() is failing in stopRuncMonitorThread() which is calling from destructor.
runcMonitorThread() is starting late,  within the time, if DobbyManager object is deleted, pthread_kill() fails because the thread is not yet started.
Need to check all test cases of DobbyManager
> [DELIA-64149] [Dobby] race condition in stopRuncMonitorThread

- CMakeLists.txt
RDK-46056: Increment Dobby version to 3.8
> RDK-46056: Increment Dobby version to 3.8

- unit_tests/L1_testing/tests/DobbyManagerTest/DaemonDobbyManagerTest.cpp
- unit_tests/L1_testing/tests/DobbyTest/DaemonDobbyTests.cpp
These are the completed use cases API list
[RDK-44357] - API list 2
DobbyManager::stopContainer()
DobbyManager::pauseContainer()
DobbyManager::resumeContainer()
DobbyManager::stateOfContainer()
DobbyManager::statsOfContainer()
[RDK-44358] - API list 3
DobbyManager::execInContainer()
DobbyManager::listContainers()
[RDK-45574] Enhancing the L1 Unit Test for Dobby.h - Added a few use cases in Dobby
Dobby::run()
Dobby::setDefaultAIDbusAddresses()
> [RDK-44357] Adding the L1 Unit Test for DobbyManager.h - API List

- daemon/lib/source/DobbyManager.cpp
Fixed setting apparmor profile and pids cgroup limit for containers started using spec files.
Check apps are using dobby_default apparmor profile.
> RDK-45299: startContainerFromSpec fix

- .github/workflows/build.yml
- AppInfrastructure/Public/Dobby/IDobbyProxy.h
- client/lib/include/DobbyProxy.h
- client/lib/source/DobbyProxy.cpp
- client/tool/source/Main.cpp
- daemon/lib/CMakeLists.txt
- daemon/lib/include/Dobby.h
- daemon/lib/source/Dobby.cpp
- daemon/lib/source/DobbyHibernate.cpp
- daemon/lib/source/DobbyHibernate.h
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/include/DobbyContainer.h
- daemon/lib/source/include/DobbyManager.h
- protocol/include/DobbyProtocol.h
- unit_tests/L1_testing/mocks/DobbyContainer.h
- unit_tests/L1_testing/mocks/DobbyManagerMock.cpp
- unit_tests/L1_testing/mocks/DobbyManagerMock.h
- unit_tests/L1_testing/mocks/dobbymanager/DobbyManager.h
- unit_tests/L1_testing/tests/DobbyManagerTest/CMakeLists.txt
- unit_tests/L1_testing/tests/DobbyManagerTest/DaemonDobbyManagerTest.cpp
Add support for container hibernation and wakeup using Memcr tool as a backend
Call:
DobbyTool hibernate <container_id>
DobbyTool wakeup <container_id>
> RDK-45706: Support for hibernate and wakeup Phase 1

- daemon/lib/source/DobbyManager.cpp
Add missing container hibernate callback call.
Run sleepy container, hibernate it using 'DobbyTool hibernate sleepy'.
Check Dobby logs, there should be:
MIL: < M:Dobby.cpp F:onContainerHibernated L:2029 > container 'sleepy'(734) hibernated
> Add missing container hibernate callback call

- settings/source/Settings.cpp
Increased default pids limit to 256.
Run container, check pids limit in /sys/fs/cgroup/pids/<container_name>/pids.max
> HBBTV-67: Increased default pids limit

- .github/workflows/L1-tests.yml
- .github/workflows/L2-tests.yml
- tests/L2_testing/test_runner/network_tests.py
- tests/L2_testing/test_runner/runner.py
Changes done:
1. In test netcat listener removed to listen the localhost and only listening port.
=> The iptables policy in the github FORWARD chain is set to DROP because the github workflow uses docker.
So, echo DOBBY_TEST | netcat [100.64.11.1](http://100.64.11.1/) 7357 -v message is not forwarding to localhost.
2. Resolved warnings in yml
3. Enabled [network.py](http://network.py/) test
Run in vagrant setup
Run in GitHub workflow.
> RDK-46381 Fix the networking related issues

- .github/workflows/L2-tests.yml
- develop/vagrant/Vagrantfile
- develop/vagrant/memcr/start_memcr.sh
- tests/L2_testing/test_runner/container_manipulations.py
- tests/L2_testing/test_runner/memcr_tests.py
- tests/L2_testing/test_runner/pid_limit_tests.py
- tests/L2_testing/test_runner/runner.py
- tests/L2_testing/test_runner/test_utils.py
RDK-47063: Add memcr L2 tests
Run L2 test using
> RDK-47063: Add memcr L2 tests

- daemon/process/CMakeLists.txt
In RDK-E, we need to skip the installation of settings file from middleware layer. So, in dobby recipe if "DONT_INSTALL_DEVICESETTINGSFILE" is set, skip the installation of settings file.
Check whether /etc/dobby.json is not present in the rootfs when build option "DONT_INSTALL_DEVICESETTINGSFILE is set.
> RDK-48618 : Skip the installation of settings file if DONT_INSTALL_DEVICESETTINGSFILE is set

- .github/workflows/codeql.yml
CodeQL action script v2 will be obsolete in December 2024, updating the workflow to use the v3 of the script.
None
Confirm CodeQL workflow runs without any warnings
> updated codeQL action script to v3

- CMakeLists.txt
- daemon/lib/source/DobbyManager.cpp
If the DobbyContainer state is not DobbyContainer::State::Running or DobbyContainer::State::Paused, the while loop keeps looping because the mContainer's data is not erased, and it is not moving to next iterator. So, check for 3 more hibernate states in the cleanupContainersShutdown() API.
> ES1-1718 : Check for hibernate states in the cleanupContainersShutdown()

- AppInfrastructure/Public/Dobby/IDobbyProxy.h
- CMakeLists.txt
- README.md
- client/lib/include/DobbyProxy.h
- client/lib/source/DobbyProxy.cpp
- client/tool/source/Main.cpp
- daemon/lib/include/Dobby.h
- daemon/lib/source/Dobby.cpp
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/include/DobbyManager.h
- protocol/include/DobbyProtocol.h
- tests/L1_testing/mocks/DobbyManagerMock.cpp
- tests/L1_testing/mocks/DobbyManagerMock.h
- tests/L1_testing/mocks/DobbyUtils.h
- tests/L1_testing/mocks/DobbyUtilsMock.cpp
- tests/L1_testing/mocks/DobbyUtilsMock.h
- tests/L1_testing/mocks/dobbymanager/DobbyManager.h
- tests/L1_testing/tests/DobbyManagerTest/DaemonDobbyManagerTest.cpp
- tests/L1_testing/tests/DobbyTest/DaemonDobbyTests.cpp
- tests/L1_testing/tests/DobbyUtilsTest/DobbyUtilsTest.cpp
- utils/include/DobbyUtils.h
- utils/include/IDobbyUtils.h
- utils/source/DobbyUtils.cpp
initial implementation of mount & unmount operations (only works on devices with kernel version > 5.2
Use the following commands to mount and unmount directories in already running containers:
```
DobbyTool mount com.sky.as.apps_com.bskyb.epgui  /mnt/usb /tmp/newmount ro,bind
DobbyTool unmount com.sky.as.apps_com.bskyb.epgui /tmp/newmount
```
> [RDK-52502]  added new mount/unmount APIs.

- AppInfrastructure/Public/Dobby/IDobbyProxy.h
- client/lib/include/DobbyProxy.h
- client/lib/source/DobbyProxy.cpp
- client/tool/source/Main.cpp
- daemon/lib/include/Dobby.h
- daemon/lib/source/Dobby.cpp
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/include/DobbyManager.h
- pluginLauncher/lib/include/DobbyRdkPluginManager.h
- pluginLauncher/lib/include/DobbyRdkPluginUtils.h
- pluginLauncher/lib/source/DobbyRdkPluginUtils.cpp
- protocol/include/DobbyProtocol.h
- tests/L1_testing/mocks/DobbyManagerMock.cpp
- tests/L1_testing/mocks/DobbyManagerMock.h
- tests/L1_testing/mocks/DobbyRdkPluginManager.h
- tests/L1_testing/mocks/DobbyRdkPluginManagerMock.cpp
- tests/L1_testing/mocks/DobbyRdkPluginManagerMock.h
- tests/L1_testing/mocks/DobbyRdkPluginUtils.h
- tests/L1_testing/mocks/DobbyRdkPluginUtilsMock.cpp
- tests/L1_testing/mocks/DobbyRdkPluginUtilsMock.h
- tests/L1_testing/mocks/dobbymanager/DobbyManager.h
- tests/L1_testing/tests/DobbyManagerTest/DaemonDobbyManagerTest.cpp
- tests/L2_testing/test_runner/annotation_tests.py
- tests/L2_testing/test_runner/runner.py
Adds "annotate()" and "removeAnnotation()" APIs to Dobby. With this method, key/value pairs can be set for containers at runtime. 
```
vagrant@dobby-vagrant-focal-arm64:~/srcDobby/build$ DobbyTool annotate sleep12 key1 value1
annotate successful for container 'sleep12'
vagrant@dobby-vagrant-focal-arm64:~/srcDobby/build$ DobbyTool annotate sleep12 key2 value2
annotate successful for container 'sleep12'
vagrant@dobby-vagrant-focal-arm64:~/srcDobby/build$ DobbyTool annotate sleep12 key3 value3
annotate successful for container 'sleep12'
vagrant@dobby-vagrant-focal-arm64:~/srcDobby/build$ DobbyTool annotate sleep12 key2 value5
annotate successful for container 'sleep12'
vagrant@dobby-vagrant-focal-arm64:~/srcDobby/build$ DobbyTool info sleep12
{
"annotations" :
{
"key1" : "value1",
"key2" : …
```
> [RDK-54420] added annotation APIs to Dobby

- pluginLauncher/lib/source/DobbyRdkPluginUtils.cpp
unshare system call is used for creating a new namespace, but in our case we just need to join an existing namespace. So, we do not need to call unshare() and can directly use setns() to switch to that namespace by opening the corresponding namespace file descriptor.
> RDK-54347 : unshare system call not required

- AppInfrastructure/Public/Common/Notifier.h
- daemon/lib/source/DobbyManager.cpp
- daemon/lib/source/include/DobbyLogRelay.h
- pluginLauncher/lib/include/DobbyRdkPluginUtils.h
- rdkPlugins/Storage/source/Storage.cpp
changed the path of the hostmnttunnel directory to include the containerID in order to properly unmount the mount tunnel directory
Confirm hostmnttunnel directory is unmounted and removed when the container stops
> RDKTV-35223: hostmounttunnel directory is not properly unmounted

- rdkPlugins/Storage/source/Storage.cpp
storage plugin postStop() hook should allow all internal modules to cleanup.
See Jira ticket
> RDKTV-35223: fix storage plugin postStop() hook error handling

- bundle/runtime-schemas/defs-plugins.json
- rdkPlugins/Networking/CMakeLists.txt
- rdkPlugins/Networking/README.md
- rdkPlugins/Networking/include/InterContainerRouting.h
- rdkPlugins/Networking/source/InterContainerRouting.cpp
- rdkPlugins/Networking/source/NetworkingPlugin.cpp
Adds the capability to the network plugin to specify input (server) and output (client) connections between container.
See the updated README.md file, as part of this PR, for description of the optional config changes.
Spawn a number of containers with combinations of input and output connections and verify you can connect between the containers.
> ENTDAI-732: Add inter container networking

- rdkPlugins/Networking/include/Netlink.h
- rdkPlugins/Networking/include/NetworkingHelper.h
- rdkPlugins/Networking/source/InterContainerRouting.cpp
- rdkPlugins/Networking/source/Netlink.cpp
- rdkPlugins/Networking/source/NetworkSetup.cpp
- rdkPlugins/Networking/source/NetworkingHelper.cpp
Found that inter-container network routing was intermittent and slow on some platforms with earlier kernels.  The problem seems to be that there was no ARP entries on the dobby0 bridge, sometimes they would show up, and sometimes a new container would still have stale entries from a previous container.
Similar problem reported here: https://github.com/moby/moby/issues/36174
To work around these issues, the NetworkPlugin is changed to add ARP rules to the cache on the dobby0 bridge when the container is started. When the container is stopped the ARP entry is removed.
Concerned about the container start time; I did some ad-hoc testing on the time it takes to add the ARP entries on broadom device and it's between 300us - 800us, so shouldn't add much to the container start time.  If this is a …
> Add ARP entires for container IPv4 address on container start.

- rdkPlugins/Minidump/source/Minidump.cpp
Minidump compression is failing due to "File name too long" issue. So, limiting the minidump file name length to 70 characters
> DELIA-67400: Trim minidump filename length

- rdkPlugins/Storage/source/DynamicMountDetails.cpp
Removing the dynamic mounts in postStop hook, since it is failing to unmount when the container is stopping
> RDKTV-35344: Dynamic mounts are failing to unmount

- bundle/lib/source/templates/OciConfigJson1.0.2-dobby.template
- bundle/lib/source/templates/OciConfigJsonVM1.0.2-dobby.template
Removes the explicit memory limit on tmpfs mounts within the container.  The inode limits are still present.
The container memory limits already apply to tmpfs files created within the container, so removing these limits doesn't remove any memory restrictions.
Some apps (flutter) can use a lot of tmpfs for storing data for hot reload and other features.
Launch a container and try to write more than 64MB to /tmp.
> ENTDAI-879: Remove the memory limit on container tmpfs.

- rdkPlugins/Storage/source/DynamicMountDetails.cpp
bug fix for dynamic mounts not getting removed when container shuts down.
see Jira ticket
- [x ] Bug fix (non-breaking change which fixes an issue)
> RDKTV-35344: Update DynamicMountDetails.cpp

- bundle/lib/source/DobbyConfig.cpp
Parsing the entirety of /sys/kernel/security/apparmor/profiles can be slow and the file can grow fairly large when complain mode is in use. Instead we can use the AppArmor sysfs interface for checking whether a profile is loaded or not. This queries the kernel directly instead of parsing the entire file.
echo -n "permprofile dobby_default" > /proc/self/attr/current
Will return an error if the profile name dobby_default is not found, if it is then no error is returned
> DELIA-67877: Use AppArmor sysfs interface for checking whether a profile is loaded
